version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music-app
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  # Node.js Backend API
  api:
    build: ./apps/api
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/music-app
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./api:/usr/src/app

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
